work_dir: ./work_dir/ntu120_alltransformer_view

# feeder
feeder: feeders.feeder_in.Feeder
train_feeder_args:
  data_path: ./data/ntu120/NTU120_XSet.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: ./data/ntu120/NTU120_XSet.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model_in.alltransformer_test.Model
model_args:
  len_parts: 6
  num_frames: 120
  num_joints: 25
  num_classes: 26
  num_heads: 3
  kernel_size: [3, 5]
  num_persons: 2
  num_channels: 3
  use_pes: True
  config: [[64,  64,  16], [64,  64,  16],
           [64,  128, 32], [128, 128, 32],
           [128, 256, 64], [256, 256, 64],
           [256, 256, 64], [256, 256, 64]]
  ter: True

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5
eval_interval: 1
# training
device: [0, 1]
batch_size: 64
test_batch_size: 64
num_epoch: 70
nesterov: True

#python main.py --config config_in/alltransformer_view.yaml
